2.0 support + no-game export
randovania/factorio-randovania-mod pull request #30
Opened 2024-10-26 13:08 UTC by henriquegemignani

Now uses the 2.0 API, dropping support to 1.1 and older.
All custom assets used by the randomizer now comes from a dedicated [assets mod](https://github.com/randovania/factorio-assets-mod) that is downloaded from the mod portal. 
Now with 2.0, the game detects missing dependencies and will prompt you to fix it. Testing it, it does takes some unusual steps so maybe a good thing to download it ourselves if it's missing.

With the assets mod and smart use of the modding APIs, it's no longer necessary to fetch any data from the game when creating the randomizer mod.

Fixes #9.
Fixes #11.

2024-10-26 13:13 UTC, Miepee commented
is it intended that the tests fail?

2024-10-26 13:18 UTC, henriquegemignani commented
Apparently I forgot to delete a test file for a removed file 🤣

2024-10-29 21:38 UTC, duncathan requested changes
I feel like I'm just missing it, but what unlocks pipes now?

2024-10-29 21:38 UTC, duncathan commented on src/factorio_randovania_mod/lua_src/prototypes/tech.lua
> +
add a comment explaining why this is necessary since it isn't exactly obvious imo

2024-10-29 21:42 UTC, henriquegemignani commented
> I feel like I'm just missing it, but what unlocks pipes now?

If I didn't mess anything, you start with them unlocked.

2024-11-01 18:34 UTC, duncathan approved these changes

2024-11-01 19:50 UTC, merged